exports.courses = [
  {
    name: 'Salsa nybörjare mån',
    previousKnowledge:
      'Vi börjar från grunden i salsa och utgår från att eleven aldrig har dansat salsa. Vi lär ut ca 15 grundturer/figurer. Inga förkunskaper krävs!',
    instructors: ['Gabriel', 'Linn'],
    startDate: '2023-01-30',
    endDate: '2023-04-17',
    startTime: '18:00',
    endTime: '19:00',
    dayOfWeek: 'Måndag',
    occasions: 10,
    price: 2000,
    danceType: 'Salsa',
    level: 0,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
  {
    name: 'Kubansk salsa 2',
    previousKnowledge:
      'Du har dansat kubansk salsa i minst 1 år. Behärskar grundläggande turer och rörelser. Dansas i 2-4 terminer.',
    instructors: ['Gabriel', 'Linn'],
    startDate: '2023-01-30',
    endDate: '2023-04-17',
    startTime: '19:00',
    endTime: '20:00',
    dayOfWeek: 'Måndag',
    occasions: 10,
    price: 2000,
    danceType: 'Cuban Salsa',
    level: 2,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
  {
    name: 'Kubansk salsa 1',
    previousKnowledge: 'Du har dansat salsa minst 1 termin/behärskar grundkursen. Dansas i 1-2 terminer.',
    instructors: ['Gabriel', 'Linn'],
    startDate: '2023-01-30',
    endDate: '2023-04-17',
    startTime: '20:00',
    endTime: '21:00',
    dayOfWeek: 'Måndag',
    occasions: 10,
    price: 2000,
    danceType: 'Cuban Salsa',
    level: 1,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
  {
    name: 'Bachata nybörjare tis',
    previousKnowledge:
      'Inga förkunskaper krävs. Vi börjar från grunden och utgår från att eleven aldrig dansat bachata. Rekommenderas att dansas i 1-2 terminer.',
    instructors: ['Hernan', 'Jeremy', 'Linda'],
    startDate: '2023-01-31',
    endDate: '2023-04-18',
    startTime: '18:30',
    endTime: '19:30',
    dayOfWeek: 'Tisdag',
    occasions: 10,
    price: 2000,
    danceType: 'Bachata',
    level: 1,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
  {
    name: 'Bachata 2 tis',
    previousKnowledge:
      'Du har dansat bachata minst 1 termin/behärskar grundkursen. Här börjar vi fokusera mer på den sensuella bachatan. Denna nivå rekommenderas att dansas i 1-2 terminer.',
    instructors: ['Hernan', 'Jeremy', 'Linda'],
    startDate: '2023-01-31',
    endDate: '2023-04-18',
    startTime: '19:30',
    endTime: '20:30',
    dayOfWeek: 'Tisdag',
    occasions: 10,
    price: 2000,
    danceType: 'Bachata',
    level: 2,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
  {
    name: 'Bachata 3',
    previousKnowledge: 'Du har dansat bachata i ett par år både socialt och på klass. Dansas i 1-3 terminer.',
    instructors: ['Hernan', 'Jeremy', 'Linda'],
    startDate: '2023-01-31',
    endDate: '2023-04-18',
    startTime: '20:30',
    endTime: '21:30',
    dayOfWeek: 'Tisdag',
    occasions: 10,
    price: 2000,
    danceType: 'Bachata',
    level: 3,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
  {
    name: 'LA salsa 1',
    previousKnowledge: 'Du har dansat salsa minst 1 termin/behärskar grundkursen. Dansas i 1-2 terminer.',
    instructors: ['Fredrica', 'Gabriel', 'Linnea'],
    startDate: '2023-02-01',
    endDate: '2023-04-19',
    startTime: '18:00',
    endTime: '19:00',
    dayOfWeek: 'Onsdag',
    occasions: 10,
    price: 2000,
    danceType: 'LA Salsa',
    level: 1,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
  {
    name: 'LA salsa 2',
    previousKnowledge:
      'Du har dansat LA salsa i minst 1 termin samt behärskar grunderna. Denna nivå rekommenderas att dansas i 1-2 terminer.',
    instructors: ['Kevin', 'Gabriel', 'Sofia'],
    startDate: '2023-02-01',
    endDate: '2023-04-19',
    startTime: '19:00',
    endTime: '20:00',
    dayOfWeek: 'Onsdag',
    occasions: 10,
    price: 2000,
    danceType: 'LA Salsa',
    level: 2,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
  {
    name: 'Kubansk salsa 2 forts.',
    previousKnowledge:
      'Du har dansat kubansk salsa i minst 1-2 år. Behärskar grundläggande turer och rörelser. Dansas i 2-4 terminer. Klassen är till för elever som gillar ett högt tempo och vill ha mycket teknik.',
    instructors: ['Kevin', 'Gabriel', 'Fredrica', 'Linnea'],
    startDate: '2023-02-01',
    endDate: '2023-04-19',
    startTime: '19:00',
    endTime: '20:00',
    dayOfWeek: 'Onsdag',
    occasions: 10,
    price: 2000,
    danceType: 'Cuban Salsa',
    level: 3,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
  {
    name: 'LA salsa 3',
    previousKnowledge:
      'För dig som dansat LA salsa både socialt och i klasser i flera år. Denna nivå rekommenderas att dansas i 1-4 terminer. Här kör vi på och utmanar våra elever med svårare turer samt snabbare tempo.',
    instructors: ['Kevin', 'Gabriel', 'Sofia'],
    startDate: '2023-02-01',
    endDate: '2023-04-19',
    startTime: '20:00',
    endTime: '21:00',
    dayOfWeek: 'Onsdag',
    occasions: 10,
    price: 2000,
    danceType: 'LA Salsa',
    level: 3,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
  {
    name: 'Salsa nybörjare ons',
    previousKnowledge:
      'Vi börjar från grunden i salsa och utgår från att eleven aldrig har dansat salsa. Vi lär ut ca 15 grundturer/figurer. Inga förkunskaper krävs!',
    instructors: ['Fredrica', 'Kevin', 'Gabriel', 'Linnea'],
    startDate: '2023-02-01',
    endDate: '2023-04-19',
    startTime: '20:00',
    endTime: '21:00',
    dayOfWeek: 'Onsdag',
    occasions: 10,
    price: 2000,
    danceType: 'Salsa',
    level: 0,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
  {
    name: 'Bachata lady style 2',
    previousKnowledge:
      'För dig som tidigare dansat lady style i 1-2 terminer. Klassen är till för dig som gillar utmaningar, teknik, styling och ett högre tempo.',
    instructors: ['Linda'],
    startDate: '2023-02-02',
    endDate: '2023-04-20',
    startTime: '17:45',
    endTime: '18:30',
    dayOfWeek: 'Torsdag',
    occasions: 10,
    price: 1500,
    danceType: 'Bachata Lady Style',
    level: 2,
    term: 'VT 2023',
    classLengthMins: 45,
    couplesDance: false,
    maxParticipants: 20,
  },
  {
    name: 'Bachata lady style 3',
    previousKnowledge:
      'För dig som tidigare dansat lady styling i minst 4 terminer. Klassen är till för elever som gillar ett högt tempo. Här jobbar vi mer med stil, känsla, musikalitet, teknik och ger dig en rejäl utmaning.',
    instructors: ['Linda'],
    startDate: '2023-02-02',
    endDate: '2023-04-20',
    startTime: '20:30',
    endTime: '21:15',
    dayOfWeek: 'Torsdag',
    occasions: 10,
    price: 1500,
    danceType: 'Bachata Ladies Style',
    level: 3,
    term: 'VT 2023',
    classLengthMins: 45,
    couplesDance: false,
    maxParticipants: 20,
  },
  {
    name: 'Bachata 5',
    previousKnowledge:
      'För dig som dansat bachata både socialt och tagit kurser i flera år. Klassen är till för elever som gillar högt tempo, teknik, styling och tycker om utmaningar. På denna nivå är turerna mer avancerade, vi går snabbare framåt och lägger mer fokus på teknik, stil och känsla.',
    instructors: ['Linda', 'Gabriel', 'Jeremy'],
    startDate: '2023-02-02',
    endDate: '2023-04-20',
    startTime: '18:30',
    endTime: '19:30',
    dayOfWeek: 'Torsdag',
    occasions: 10,
    price: 2000,
    danceType: 'Bachata',
    level: 5,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
  {
    name: 'Bachata 4',
    previousKnowledge:
      'Du har dansat bachata både socialt och på klass i flera år. Klassen är till för elever som gillar högt tempo, teknik, styling och tycker om utmaningar.',
    instructors: ['Linda', 'Gabriel', 'Jeremy'],
    startDate: '2023-02-02',
    endDate: '2023-04-20',
    startTime: '19:30',
    endTime: '20:30',
    dayOfWeek: 'Torsdag',
    occasions: 10,
    price: 2000,
    danceType: 'Bachata',
    level: 4,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
  {
    name: 'Bachata lady style 1',
    previousKnowledge:
      'Du har dansat bachata i minst 1-2 terminer. Klassen är till för dig som gillar teknik, styling och tycker om utmaningar.',
    instructors: ['Linda'],
    startDate: '2023-02-05',
    endDate: '2023-04-23',
    startTime: '13:00',
    endTime: '13:45',
    dayOfWeek: 'Söndag',
    occasions: 10,
    price: 1500,
    danceType: 'Bachata Ladies Style',
    level: 1,
    term: 'VT 2023',
    classLengthMins: 45,
    couplesDance: false,
    maxParticipants: 20,
  },
  {
    name: 'Bachata 2 sön',
    previousKnowledge:
      'Du har dansat bachata minst 1 termin/behärskar grundkursen. Här börjar vi fokusera mer på den sensuella bachatan. Denna nivå rekommenderas att dansas i 1-2 terminer.',
    instructors: ['Linda', 'Gabriel'],
    startDate: '2023-02-05',
    endDate: '2023-04-23',
    startTime: '14:00',
    endTime: '15:00',
    dayOfWeek: 'Torsdag',
    occasions: 10,
    price: 2000,
    danceType: 'Söndag',
    level: 2,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
  {
    name: 'Bachata nybörjare sön',
    previousKnowledge:
      'Inga förkunskaper krävs. Vi börjar från grunden och utgår från att eleven aldrig dansat bachata. Rekommenderas att dansas i 1-2 terminer.',
    instructors: ['Linda', 'Gabriel'],
    startDate: '2023-02-05',
    endDate: '2023-04-23',
    startTime: '15:00',
    endTime: '16:00',
    dayOfWeek: 'Söndag',
    occasions: 10,
    price: 2000,
    danceType: 'Bachata',
    level: 1,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
  {
    name: 'Salsa nybörjare sön',
    previousKnowledge:
      'Vi börjar från grunden i salsa och utgår från att eleven aldrig har dansat salsa. Vi lär ut ca 15 grundturer/figurer. Inga förkunskaper krävs!',
    instructors: ['Gabriel'],
    startDate: '2023-02-05',
    endDate: '2023-04-23',
    startTime: '16:00',
    endTime: '17:00',
    dayOfWeek: 'Söndag',
    occasions: 10,
    price: 2000,
    danceType: 'Salsa',
    level: 0,
    term: 'VT 2023',
    classLengthMins: 60,
    couplesDance: true,
    maxParticipants: 30,
  },
]
